# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sift < Formula
  desc "Build LLM workflows on the command line"
  homepage "https://github.com/chriscorrea/sift"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/chriscorrea/sift/releases/download/v0.1.0/sift_0.1.0_darwin_amd64.tar.gz"
      sha256 "fe3bd120b4aad7017078dd851d7dbcdd5ee837469a4696b35e868956a2f64255"

      def install
        bin.install "sift"
      end
    end
    on_arm do
      url "https://github.com/chriscorrea/sift/releases/download/v0.1.0/sift_0.1.0_darwin_arm64.tar.gz"
      sha256 "86db05a53f7dcc645c4cdb62bf4f4cce59d4a8a12682fbb20544a5f17177d5d6"

      def install
        bin.install "sift"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/sift/releases/download/v0.1.0/sift_0.1.0_linux_amd64.tar.gz"
        sha256 "ce6c6814561e4a6b7c14c58ed87fb9cff3ea2895b18fb2153ae3e90ebfd27566"

        def install
          bin.install "sift"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/sift/releases/download/v0.1.0/sift_0.1.0_linux_arm64.tar.gz"
        sha256 "5d9b7c81db318ae80610c3b93bda934e9afadb35bc23d63a869ff88b89615995"

        def install
          bin.install "sift"
        end
      end
    end
  end

  test do
    system "#{bin}/sift --help"
  end
end
