# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sift < Formula
  desc "Strips tags from html and extract clean, structured text on the command line"
  homepage "https://github.com/chriscorrea/sift"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/chriscorrea/sift/releases/download/v0.1.1/sift_0.1.1_darwin_amd64.tar.gz"
      sha256 "26564a0a8ee49bf1dd53ca28e0feae1688c942aacd7b5722ec8d7218973fdf86"

      def install
        bin.install "sift"
        # man1.install "man/sift.1"
      end
    end
    on_arm do
      url "https://github.com/chriscorrea/sift/releases/download/v0.1.1/sift_0.1.1_darwin_arm64.tar.gz"
      sha256 "cb10a7d96fb530d34e519b17527a077b399b0f66d0d3c974043ffe41f11240ed"

      def install
        bin.install "sift"
        # man1.install "man/sift.1"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/sift/releases/download/v0.1.1/sift_0.1.1_linux_amd64.tar.gz"
        sha256 "1aa69d22f7f333ead145d2b88988f92e227925de015a82ad4472560423cd8ff9"

        def install
          bin.install "sift"
          # man1.install "man/sift.1"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/chriscorrea/sift/releases/download/v0.1.1/sift_0.1.1_linux_arm64.tar.gz"
        sha256 "3588bb6ece72ed21824dac52b3d00b1ad0846a6c45473dd60c39c44bcde7814c"

        def install
          bin.install "sift"
          # man1.install "man/sift.1"
        end
      end
    end
  end

  test do
    system "#{bin}/sift --help"
  end
end
